server:
  port: 8899

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

#logging:
#  level:
#  org.apache.zookeeper.ClientCnxn: WARN

management:
  security:
    enabled: false

spring:
  application:
    name: tenant-service
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: 192.168.99.100:2181