server:
  port: 8080

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN


spring:
  application:
    name: GreetingConsumer
  cloud:
    zookeeper:
      connect-string: 192.168.99.100:2181
